version: "3"

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
            # - ./django_packages:/usr/local/lib/python3.7/site-packages/django
        command: >
         sh -c "python manage.py runserver 0.0.0.0:8000"

